### ISSUE TITLE
[fix] - 헤더 title 미적용

### ISSUE THREAD

**Issue by MrMirror21** [Team-inglo/Giggle-Web#26]
## 🛠️ Description

헤더 컴포넌트에 title property가 미적용 중으로 보입니다.
<img width="402" alt="스크린샷 2024-10-22 오후 8 27 33" src="https://github.com/user-attachments/assets/87b1d6e0-7a1d-4b83-8cb4-71dbebb4c976">
<img width="673" alt="스크린샷 2024-10-22 오후 8 28 12" src="https://github.com/user-attachments/assets/d81ee7a3-0e0e-4ea9-9d73-07a4874f8179">
<img width="476" alt="스크린샷 2024-10-22 오후 8 15 51" src="https://github.com/user-attachments/assets/1fec6941-ab1d-43dd-bbb8-3579cbc33ef9">

## 📝 To do

- [x] title property 적용되도록 수정
- [x] 뒤로가기 버튼만 있을 경우에 title 가운데 정렬되도록

**Comment by naarang** [comment]
아... title이 아니라 {title}을 했어야돼네요! 수정하겠습니다ㅠ
